news/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('post.urls'))
    ]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path,include
from .views import index,post,Indian_News,Entertainment,World_News,\
    Economics,Sports,Technology,Life_Style,Science_and_Environment,create_post,SearchView,\
    category_news,photos,contact
app_name ='post'
urlpatterns = [
    path('',index,name='index'),
    path('Indian_News/',Indian_News,name='Indian_News'),
    path('World_News/',World_News,name='World_News'),
    path('Economics/',Economics,name='Economics'),
    path('Sports/',Sports,name='Sports'),
    path('entertainment/',Entertainment,name='Entertainment'),
    path('Technology/',Technology,name='Technology'),
    path('Life_Style/',Life_Style,name='Life_Style'),
    path('Science_and_Environment/',Science_and_Environment,name='Science_and_Environment'),
    path('photos/',photos,name='photos'),
    path('contact/',contact,name='contact'),

    path('news/<cate_gory>',category_news,name='category_news'),

    path('search',SearchView.as_view(),name='search'),

    path('post/<slug>/',post,name='post'),
    path('create_post',create_post,name='create_post'),



]

post/models.py
from django.db import models
from django.utils.timezone import now
from django.db.models import Q

# Create your models here.
class PostQuerySet(models.QuerySet):
    def search(self, query=None):
        qs = self
        if query is not None:
            or_lookup = (
                         Q(title__icontains = query) |
                         Q(post__icontains=query) |
                         Q(category__category__icontains=query)
                         )
            qs = qs.filter(or_lookup).distinct()  # distinct() is often necessary with Q lookups
        return qs

    def rank_1(self):
        return self.filter(rating='5')


class PostManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model,using=self._db)

    def search(self,query=None):
        return self.get_queryset().search(query=query)

    def rank_1(self):
        return self.get_queryset().rank_1()



class CategoryQuerySet(models.QuerySet):
    def search(self, query=None):
        qs = self
        if query is not None:
            or_lookup = (
                         Q(category__icontains = query) |
                         Q(date__icontains=query)
                         )
            qs = qs.filter(or_lookup).distinct()  # distinct() is often necessary with Q lookups
        return qs

class CategoryManager(models.Manager):
    def get_queryset(self):
        return CategoryQuerySet(self.model,using=self._db)

    def search(self,query=None):
        return self.get_queryset().search(query=query)

class Category(models.Model):
    category=models.CharField(max_length=50)
    rating=models.IntegerField(default=0)
    date = models.DateTimeField(default=now)

    objects = CategoryManager()

    def __str__(self):
        return self.category

class Post(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    title=models.CharField(max_length=500,blank=True)
    post = models.TextField(blank=True)
    post_para_2 = models.TextField(blank=True)
    post_para_3 = models.TextField(blank=True)
    captions=models.TextField(blank=True)
    captions_para_2 = models.TextField(blank=True)
    captions_para_3 = models.TextField(blank=True)
    quote=models.CharField(max_length=200,blank=True)
    quote_by=models.CharField(max_length=100,blank=True)
    image=models.ImageField(upload_to='post_image/%Y/%m/%d/',blank=True)
    date= models.DateTimeField(default=now)
    related_post_1 = models.CharField(max_length=100,blank=True)
    related_link_1 = models.CharField(max_length=100,blank=True)
    related_post_2 = models.CharField(max_length=100,blank=True)
    related_link_2 = models.CharField(max_length=100,blank=True)
    related_post_3 = models.CharField(max_length=100,blank=True)
    related_link_3 = models.CharField(max_length=100,blank=True)
    rating=models.IntegerField(default=0)

    slug =models.SlugField(unique=True,max_length=100)

    objects=PostManager()

    def __str__(self):
        return self.title

post/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write the title of the book...'
        }
    ),required=False)
    post = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'write the post'
        }
    ),required=False)
    post_para_2 = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'write the post'
        }
    ),required=False)
    post_para_3 = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'write the post'
        }
    ),required=False)
    captions = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'write the post'
        }
    ),required=False)
    captions_para_2 = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'write the post'
        }
    ),required=False)
    captions_para_3 = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'write the post'
        }
    ),required=False)
    quote = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'mention about the subject...'
        }
    ),required=False)
    quote_by = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'mention about the subject...'
        }
    ),required=False)

    related_post_1 = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'write the title of related post'
        }
    ),required=False)
    related_link_1 = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter the link of related post'
        }
    ),required=False)
    related_post_2 = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'write the title of related post'
        }
    ),required=False)
    related_link_2 = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter the link of related post'
        }
    ),required=False)
    related_post_3 = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'write the title of related post'
        }
    ),required=False)
    related_link_3 = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter the link of related post'
        }
    ),required=False)

    class Meta:
        model = Post
        fields = ('category', 'title','post', 'post_para_2','post_para_3','captions',
                  'captions_para_2','captions_para_3', 'quote','quote_by',
                  'image','related_post_1', 'related_link_1','related_post_2',
                  'related_link_2', 'related_post_3', 'related_link_3', 'rating')

post/views.py
from django.shortcuts import render,redirect,reverse,get_object_or_404
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView,View
from django.core.paginator import Paginator
from .models import Post,Category
from django.utils.timezone import now
from urllib.parse import quote_plus
from .forms import PostForm
from django.utils.text import slugify
from itertools import chain

# Create your views here.
def index(request):
    rank_1=Post.objects.rank_1().order_by('-date')[:1]
    recent_post=Post.objects.all().order_by('-date')[:3]
    categories=Category.objects.all()
    dictionary = {}
    for category in categories:
        post_list=Post.objects.filter(category=category).order_by('-date')[:4]
        dictionary[category]=post_list
    popular_post=Post.objects.filter(rating='3').order_by('-date')[:5]
    trending_post=Post.objects.filter(rating='4').order_by('-date')[:5]
    return render(request, 'post/index.html',{'now':now(),'rank_1':rank_1,'recent_post':recent_post,
                                              'dictionary':dictionary,'popular_post':popular_post,
                                              'trending_post':trending_post,})

def Indian_News(request):
    category = Category.objects.get(category='Indian News')
    post_list = Post.objects.filter(category=category).order_by('-date')
    popular_post = Post.objects.filter(rating='3').order_by('-date')[:5]
    trending_post = Post.objects.filter(rating='4').order_by('-date')[:5]
    paginator = Paginator(post_list, 20)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)
    return render(request, 'post/category_three.html', {'now':now(),'post_list': post_list,
                                                        'category':category,'popular_post':popular_post,
                                                        'trending_post':trending_post,})

def World_News(request):
    category = Category.objects.get(category='World News')
    post_list = Post.objects.filter(category=category).order_by('-date')
    popular_post = Post.objects.filter(rating='3').order_by('-date')[:5]
    trending_post = Post.objects.filter(rating='4').order_by('-date')[:5]
    paginator = Paginator(post_list, 20)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)
    return render(request, 'post/category_three.html',{'now': now(), 'post_list': post_list,
                                                       'category': category, 'popular_post': popular_post,
                                                       'trending_post': trending_post,})
def Economics(request):
    category = Category.objects.get(category='Economics')
    post_list = Post.objects.filter(category=category).order_by('-date')
    popular_post = Post.objects.filter(rating='3').order_by('-date')[:5]
    trending_post = Post.objects.filter(rating='4').order_by('-date')[:5]
    paginator = Paginator(post_list, 20)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)
    return render(request, 'post/category_three.html',
                  {'now': now(), 'post_list': post_list, 'category': category, 'popular_post': popular_post,
                   'trending_post': trending_post,})

def Sports(request):
    category = Category.objects.get(category='Sports')
    post_list = Post.objects.filter(category=category).order_by('-date')
    popular_post = Post.objects.filter(rating='3').order_by('-date')[:5]
    trending_post = Post.objects.filter(rating='4').order_by('-date')[:5]
    paginator = Paginator(post_list, 20)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)
    return render(request, 'post/category_three.html',
                  {'now': now(), 'post_list': post_list, 'category': category, 'popular_post': popular_post,
                   'trending_post': trending_post,})

def Entertainment(request):
    category=Category.objects.get(category='Entertainment')
    post_list = Post.objects.filter(category=category).order_by('-date')
    popular_post = Post.objects.filter(rating='3').order_by('-date')[:5]
    trending_post = Post.objects.filter(rating='4').order_by('-date')[:5]
    paginator = Paginator(post_list, 20)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)
    return render(request, 'post/category_three.html',
                  {'now': now(), 'post_list': post_list, 'category': category, 'popular_post': popular_post,
                   'trending_post': trending_post,})

def Technology(request):
    category = Category.objects.get(category='Technology')
    post_list = Post.objects.filter(category=category).order_by('-date')
    popular_post = Post.objects.filter(rating='3').order_by('-date')[:5]
    trending_post = Post.objects.filter(rating='4').order_by('-date')[:5]
    paginator = Paginator(post_list, 20)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)
    return render(request, 'post/category_three.html',
                  {'now': now(), 'post_list': post_list, 'category': category, 'popular_post': popular_post,
                   'trending_post': trending_post,})
def Life_Style(request):
    category = Category.objects.get(category='Life Style')
    post_list = Post.objects.filter(category=category).order_by('-date')
    popular_post = Post.objects.filter(rating='3').order_by('-date')[:5]
    trending_post = Post.objects.filter(rating='4').order_by('-date')[:5]
    paginator = Paginator(post_list, 20)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)
    return render(request, 'post/category_three.html',
                  {'now': now(), 'post_list': post_list, 'category': category, 'popular_post': popular_post,
                   'trending_post': trending_post,})

def Science_and_Environment(request):
    category = Category.objects.get(category='Science and Environment')
    post_list = Post.objects.filter(category=category).order_by('-date')
    popular_post = Post.objects.filter(rating='3').order_by('-date')[:5]
    trending_post = Post.objects.filter(rating='4').order_by('-date')[:5]
    paginator = Paginator(post_list, 20)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)
    return render(request, 'post/category_three.html',
                  {'now': now(), 'post_list': post_list, 'category': category, 'popular_post': popular_post,
                   'trending_post': trending_post,})


def category_news(request,cate_gory):
    category = Category.objects.get(category=cate_gory)
    post_list = Post.objects.filter(category=category).order_by('-date')
    popular_post = Post.objects.filter(rating='3').order_by('-date')[:5]
    trending_post = Post.objects.filter(rating='4').order_by('-date')[:5]
    paginator = Paginator(post_list, 20)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)
    return render(request, 'post/category_three.html',
                  {'now': now(), 'post_list': post_list, 'category': category, 'popular_post': popular_post,
                   'trending_post': trending_post,})

def post(request,slug):
    post = get_object_or_404(Post,slug=slug)
    share_string=quote_plus(post.title)
    return render(request, 'post/single_center.html',{'now':now(),'post':post,'share_string':share_string})

def photos(request):
    post = Post.objects.all().order_by('-date')

    paginator = Paginator(post, 20)
    page = request.GET.get('page')
    post = paginator.get_page(page)

    return render(request, 'post/photos.html',{'post':post})

def contact(request):
    return render(request, 'post/contact.html', )



def create_post(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PostForm(request.POST, request.FILES)
            if form.is_valid():
                post = form.save(commit=False)
                post.slug=slugify(post.title)
                post.save()
                slug = '%s %s' % (post.title, post.id)
                post.slug = slugify(slug)
                post.save()
                return redirect(reverse('post:index'))
        else:
            form = PostForm
        return render(request,'post/post_form.html',{'form': form})
    else:
        return redirect(reverse('post:index'))

################
# new search view
################
class SearchView(ListView):
    template_name = 'post/searchresult.html'
    paginate_by = 20
    count = 0

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['count'] = self.count or 0
        context['query'] = self.request.GET.get('q')
        return context

    def get_queryset(self):
        request = self.request
        query = request.GET.get('q', None)

        if query is not None:
            post_results= Post.objects.search(query)
            category_result=Category.objects.search(query)

            # combine querysets
            queryset_chain = chain(
                post_results,category_result
            )
            qs = sorted(queryset_chain,
                        key=lambda instance: instance.pk,
                        reverse=True)
            self.count = len(qs) # since qs is actually a list
            return qs
        return Post.objects.none() # just an empty queryset as default

post/templates/post/index.html
{% extends 'post/base.html'%}
{% block body %}
<!--big-article-->
{% for post in rank_1 %}
<article class="big-article">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="ciz-thumb">
                <a href="{% url 'post:post' post.slug %}">
                    {% if post.image %}
                    <img alt="" src="{{post.image.url}}" />
                    {% endif %}
                </a>
            </div>
        </div>
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="big-article-bar">
                <div class="post-meta">
                    <span class="post-category">
                        <a href="{% url 'post:category_news' post.category %}">{{post.category}}</a>
                    </span>
                    <em>/</em>
                    <span class="post-date">
                        {{post.date}}
                    </span>
                </div>
                <div class="share-posts">
                    <span>
                        Share
                    </span>

                    <a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}" target="_blank" class="facebook"><i class="fa fa-facebook"></i></a>
                    <a href="https://twitter.com/home?status={{ share_string }}%20{{request.build_absolute_uri}}" target="_blank" class="twitter"><i class="fa fa-twitter"></i></a>
                </div>
            </div>
            <h1>
                <a href="{% url 'post:post' post.slug %}">
                    {{post.title|safe}}
                </a>
            </h1>
            <p>{{post.post|truncatewords:100|safe}}</p>
            <a href="{% url 'post:post' post.slug %}" class="readmore">READ MORE</a>
        </div>
    </div>
</article>
{% endfor %}
<!--recent posts-->
<div class="box-caption">
    <h2><span> RECENT POSTS</span></h2>
</div>
<!--three recent posts-->
<div class="three-articles">
    <div class="row">
        {% for post in recent_post %}
            <div class="col-md-4 col-xs-12">
                <article class="three-item">
                    {% if post.image %}
                    <div class="ciz-thumb" style="height:300px;">
                        <a href="{% url 'post:post' post.slug %}"><img alt="" src="{{post.image.url}}" style="max-height:300px; margin-left:auto;margin-right:auto;" /></a>
                    </div>
                    {% endif %}
                    <div class="post-meta">
                        <span class="post-category">
                            <a href="{% url 'post:category_news' post.category %}">{{post.category}}</a>
                        </span>
                        <em>/</em>
                        <span class="post-date">
                            {{post.date}}
                        </span>
                    </div>
                    <h4><a href="{% url 'post:post' post.slug %}">{{post.title|safe}}</a></h4>
                </article>
            </div>
        {% endfor %}
    </div>
</div>
<!--cols-->
<div class="cols">
    <!--colleft-->
    <div class="colleft">
        {% for category,post_list in dictionary.items %}
            {% if post_list %}
                <!--post item-->
                <article class="ciz-post">
                    <div class="post-meta">
                        <span class="post-category">
                            <a href="{% url 'post:category_news' category %}">{{category}} </a>
                        </span>
                        <em>/</em>
                        <span class="post-date">
                            {{post_list.0.date}}
                        </span>
                        <div class="share-posts">
                            <span>
                                Share
                            </span>
                            <a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}" target="_blank" class="facebook"><i class="fa fa-facebook"></i></a>
                            <a href="https://twitter.com/home?status={{ share_string }}%20{{request.build_absolute_uri}}" target="_blank" class="twitter"><i class="fa fa-twitter"></i></a>
                        </div>
                    </div>
                    <h2>
                        <a href="{% url 'post:post' post_list.0.slug %}">{{post_list.0.title|safe}} </a>
                    </h2>
                    <div class="ciz-thumb" style="max-height:600px;overflow: auto;">
                        <a href="{% url 'post:post' post_list.0.slug %}">
                            <img alt="{{post_list.0.title}}" src="{% if post_list.0.image%}{{post_list.0.image.url}}{% endif %}" class="w3-image"/>
                        </a>
                    </div>
                    <div class="post-content">
                        <p>
                            {{post_list.0.post|truncatewords:100|safe}}
                        </p>
                    </div>
                    <a href=" {% url 'post:post' post_list.0.slug %} " class="post-readmore">Read more</a>
                    <div class="box-caption box-caption-small">
                        <h2><span> in category of {{category}}</span></h2>
                    </div>
                    <div class="three-articles">
                        <div class="row">
                            {% if post_list.1 %}
                            <div class="col-md-4 col-xs-12">
                                <article class="three-item">
                                    <div class="ciz-thumb">
                                        <a href=" {% url 'post:post' post_list.1.slug %} "><img alt="{{post_list.1.title|safe}}" src="{% if post_list.1.image%}{{post_list.1.image.url}}{% endif %}" /></a>
                                    </div>
                                    <h5><a href=" {% url 'post:post' post_list.1.slug %} ">{{post_list.1.title|safe}}</a></h5>
                                </article>
                            </div>
                            {% endif %}
                            {% if post_list.2 %}
                            <div class="col-md-4 col-xs-12">
                                <article class="three-item">
                                    <div class="ciz-thumb">
                                        <a href=" {% url 'post:post' post_list.2.slug %} "><img alt="{{post_list.2.title}}" src="{% if post_list.2.image %}{{post_list.2.image.url}}{%endif%}" /></a>
                                    </div>
                                    <h5><a href=" {% url 'post:post' post_list.2.slug %} ">{{post_list.2.title|safe}}</a></h5>
                                </article>
                            </div>
                            {% endif %}
                            {% if post_list.3 %}
                            <div class="col-md-4 col-xs-12">
                                <article class="three-item">
                                    <div class="ciz-thumb">
                                        <a href=" {% url 'post:post' post_list.3.slug %} "><img alt="{{post_list.3.title}}" src="{% if post_list.3.image %}{{post_list.3.image.url}}{% endif %}" /></a>
                                    </div>
                                    <h5><a href=" {% url 'post:post' post_list.3.slug %} ">{{post_list.3.title|safe}}</a></h5>
                                </article>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </article>
            {% endif %}
        {% endfor %}
    </div>
    <!--colright-->
    <div class="colright">
        <!-- dailies-->
        <!--<div class="dailies">-->
            <!--<div class="widget-title widget-title-white ">-->
                <!--<span>-->
                    <!--DAILIES-->
                <!--</span>-->
            <!--</div>-->
            <!--<div class="dailies-content">-->
                <!--<div class="owl-carousel owl-dailies">-->
                    <!--<div>-->
                        <!--<a href="single_center.html">-->
                            <!--<div class="ciz-thumb">-->
                                <!--<img alt="" src="http://www.cizthemes.com/template/ciznews/images/w3.jpg" />-->
                            <!--</div>-->
                        <!--</a>-->
                        <!--<h3>-->
                            <!--<a href="single_center.html">Satisne vobis videor pro meo iure in vestris auribus commentatus</a>-->
                        <!--</h3>-->
                    <!--</div>-->
                    <!--<div>-->
                        <!--<a href="single_center.html">-->
                            <!--<div class="ciz-thumb">-->
                                <!--<img alt="" src="http://www.cizthemes.com/template/ciznews/images/w9.jpg" />-->
                            <!--</div>-->
                        <!--</a>-->
                        <!--<h3>-->
                            <!--<a href="single_center.html">Donec sollicitudin molestie malesuada.d</a>-->
                        <!--</h3>-->
                    <!--</div>-->
                <!--</div>-->
            <!--</div>-->
        <!--</div>-->
        <!-- popular posts-->
        <div class="popular-box">
            <div class="widget-title">
                <span>
                    POPULAR POSTS
                </span>
            </div>
            <div class="list-popular">
                {% for post in popular_post %}
                <article class="popular-item">
                    <div class="ciz-thumb">
                        <a href="{% url 'post:post' post.slug %}">
                            <img alt="{{post.title}}" src="{% if post.image %}{{post.image.url}} {% endif %}">
                        </a>
                    </div>
                    <div class="post-meta">
                        <span class="post-category">
                            <a href="{% url 'post:category_news' post.category %}">{{post.category}}</a>
                        </span>
                        <em>/</em>
                        <span class="post-date">
                            {{post.date}}
                        </span>
                    </div>
                    <h5><a href="{% url 'post:post' post.slug %}">{{post.title|safe}}</a></h5>
                </article>
                {% endfor %}
            </div>
        </div>
        <!-- connect us-->
        <div class="connect-us">
            <div class="widget-title">
                <span>
                    CONNECT & FOLLOW
                </span>
            </div>
            <ul class="list-social-icon">
                <li>
                    <a href="#" class="facebook">
                        <i class="fa fa-facebook"></i>
                    </a>
                </li>
                <li>
                    <a href="#" class="twitter">
                        <i class="fa fa-twitter"></i>
                    </a>
                </li>
                <li>
                    <a href="#" class="google">
                        <i class="fa fa-google"></i>
                    </a>
                </li>
                <li>
                    <a href="#" class="youtube">
                        <i class="fa fa-youtube-play"></i>
                    </a>
                </li>
                <li>
                    <a href="#" class="pinterest">
                        <i class="fa fa-pinterest-p"></i>
                    </a>
                </li>

            </ul>
        </div>
        <!-- subcribe box-->
        <div class="subcribe-box">
            <h3>NEWSLETTER</h3>
            <p>Enter your email address below to subscribe to my newsletter</p>
            <input type="text" placeholder="Your email address..." />
            <button class="my-btn">Subscribe</button>
        </div>
        <!-- trend post-->
        <div class="trend-box trend-box-affix" data-spy="affix">
            <div class="widget-title">
                <span>
                    TREND
                </span>
            </div>
            <ul class="list-trend">
                {% for post in trending_post %}
                <li class="trend-item">
                    <span class="number">
                        <img alt="" src="{{post.image.url}}" />
                        0{{forloop.counter}}
                    </span>
                    <h5><a href="{% url 'post:post' post.slug %}">{{post.title|safe}}</a></h5>
                </li>
                {% endfor %}
            </ul>
        </div>
        <!-- advertisement-->
        <div class="ads hidden-sm hidden-xs hidden ">
            <p>advertisement</p>
            <img alt="" src="http://www.cizthemes.com/template/ciznews/images/ads.jpg" class="img-responsive" />
        </div>
    </div>
    <div class="clearfix"></div>
</div>
{% endblock body%}

post/templates/post/searchresult.html
{% extends 'post/base.html'%}
{% load class_name %}
{% block title%}Search result{% endblock %}
{% block body %}
<section class="white-bg">
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
            <div class="w3-container">
                  <h3 class="widget-title">results for <b>{{query}}</b></h3>
                  <ul class="w3-ul w3-card">
                      {% for object in object_list %}
                            {% with object|class_name as klass %}
                              {% if klass == 'Post' %}
                              <li>
                                  <a href="{% url 'post:post' object.slug %}" target="_blank">News: {{ object.title }}</a>
                              </li>
                                {% elif klass == 'Category' %}
                                <li>
                                  <a href="{% url 'post:category_news' object.category %}" target="_blank"> All {{ object.category }} News</a>
                              </li>
                              {% else %}
                                      <li>
                                          <a href=''>{{ object }} | {{ object|class_name }}</a>
                                      </li>
                                {% endif %}
                            {% endwith %}
                        {% empty %}
                        {% endfor %}
                  </ul>
              </div>
        </div>

     </div>
</div>
    </section>
{% endblock %}